---

- hosts: all
  become: true
  roles:
    - nginxinc.nginx
  vars_files:
    - vars/nginx-conf.yml
  tasks:
    - name: create backend folder
      file:
        path: /usr/share/backend/html
        state: directory
    - name: copy backend file
      copy:
        src: webpages/backend.html
        dest: /usr/share/backend/html/index.html
    - name: create frontend folder
      file:
        path: /usr/share/frontend/html
        state: directory
    - name: copy frontend file
      copy:
        src: webpages/frontend.html
        dest: /usr/share/frontend/html/index.html