---

- hosts: all
  become: true
  roles:
    - nginxinc.nginx
    - rvm.ruby
  vars_files:
    - vars/nginx-conf.yml
  vars:
    - rvm1_user: 'root'
  tasks:
    - name: create backend folder
      file:
        path: /usr/etc/website/html
        state: directory
    - name: download codedeploy
      get_url:
        url: https://aws-codedeploy-eu-west-1.s3.amazonaws.com/latest/install
        dest: /tmp
        mode: '0775'
    - name: install codedeploy
      command: /tmp/install auto